Models/Computer.cs
namespace MvcLabManager.Models;

public class Computer
{
    public int Id { get; set; }
    public string Ram { get; set; }
    public string Processor { get; set; }

    public Computer() {}


    public Computer(int id , string ram , string processor)
    {
        Id = id;
        Ram = ram ; 
        Processor = processor;
    }
}

Models/ErrorViewModel.cs
namespace MvcLabManager.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Lab.cs
using System.ComponentModel.DataAnnotations;
namespace MvcLabManager.Models;

public class Lab 
{
    [Required]
    public int Id { get; set; }

    [Required]
    public int Number { get; set; }

    [Required]
    public string Name { get; set; }

    [Required]
    public string Block { get; set; }

    public Lab() {}

    public Lab(int id, int number, string name, string block)
    {
        Id = id;
        Number = number;
        Name = name;
        Block = block;
    }
}

Models/LabManagerContext.cs
using Microsoft.EntityFrameworkCore;

namespace MvcLabManager.Models;

public class LabManagerContext : DbContext
{
    public DbSet<Computer> Computers {get; set; }
    public DbSet<Lab> Labs {get; set; }
    
    public LabManagerContext(DbContextOptions<LabManagerContext> options) : base(options)
    {

    }
}

Controllers/ComputerController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLabManager.Models;

namespace MvcLabManager.Controllers;

public class ComputerController : Controller 
{
    private readonly LabManagerContext _context;

    public ComputerController(LabManagerContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        return View(_context.Computers);
    }

    public IActionResult Show(int id)
    {
        Computer computer = _context.Computers.Find(id);

        if(computer == null)
        {
            return NotFound();
        }

        return View(computer);
    }

   

    public IActionResult Update (int id)
    {
        Computer computer = _context.Computers.Find(id);

        if(computer == null)
        {
            return NotFound();
        }

        return View(computer);
    }

   
     public IActionResult Update (int id, [FromForm] string ram, [FromForm] string processor)
    {
        Computer computer = _context.Computers.Find(id);

        if(computer == null)
        {
            return NotFound();
        }

        computer.Ram = ram;
        computer.Processor = processor;
    
        _context.Computers.Update(computer);
        _context.SaveChanges();

        return RedirectToAction("Index");
    }

    public IActionResult Delete (int id)
    {
        Computer computer = _context.Computers.Find(id);

        if(computer == null)
        {
            return NotFound();
        }

        _context.Computers.Remove(computer);
        _context.SaveChanges();

        return View(computer);
    }
     public IActionResult Create (Computer computer)
    {
        if(!ModelState.IsValid) 
        {
             return View(computer);
        }

        _context.Computers.Add(computer);
        _context.SaveChanges();   

        return RedirectToAction("Index");
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvcLabManager.Models;

namespace MvcLabManager.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LabController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLabManager.Models;

namespace MvcLabManager.Controllers;

public class LabController : Controller 
{
    private readonly LabManagerContext _context;

    public LabController(LabManagerContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        return View(_context.Labs);
    }

    public IActionResult Show(int id)
    {
        Lab lab = _context.Labs.Find(id);

        if(lab == null)
        {
            return NotFound();
        }

        return View(lab);
    }

    public IActionResult Create (Lab lab)
    {
        if(!ModelState.IsValid) 
        {
            return View(lab);
        }

         _context.Labs.Add(lab);
         _context.SaveChanges();

         return RedirectToAction("Index");
    }

     public IActionResult Update (int id)
    {
        Lab lab = _context.Labs.Find(id);

        if(lab == null)
        {
            return NotFound();
        }

        return View(lab);
    }

    [HttpPost]

     public IActionResult Update (int id, [FromForm] int number, [FromForm] string name, [FromForm] string block)
    {
        Lab lab = _context.Labs.Find(id);

        if(lab == null)
        {
            return NotFound();
        }

        lab.Number = number;
        lab.Name = name;
        lab.Block = block;

        _context.Labs.Update(lab);
        _context.SaveChanges();

        return RedirectToAction("Index");
    }

    public IActionResult Delete (int id)
    {
       Lab lab = _context.Labs.Find(id);

        if(lab == null)
        {
            return NotFound();
        }

        _context.Labs.Remove(lab);
        _context.SaveChanges();

        return View(lab);
    }
}

Views/Computer/Create.cshtml
@model MvcLabManager.Models.Computer

@{
    ViewData["Title"] = "Registrar Computador";
}
<h1>@ViewData["Title"]</h1>


    <form method="post">
        <p>
            <label for="id"><strong>Id:</strong></label>
            <input type="text" name="id" id="id">
            <span asp-validation-for="Id" class="text-danger" ></span>
        </p>
        <p>
            <label for="ram"><strong>RAM: </strong></label>
            <input type="text" name="ram" id="ram">
            <span asp-validation-for="Ram" class="text-danger" ></span>
        </p>
          <p>
            <label for="processor"><strong>Processador: </strong></label>
            <input type="text" name="processor" id="processor">
            <span asp-validation-for="Processor" class="text-danger" ></span>
        </p>

        <button asp-controller="Computer" asp-action="Create" class="btn btn-outline-success">Registrar</button>
    </form>

Views/Computer/Delete.cshtml
@model MvcLabManager.Models.Computer

@{
    ViewData["Title"] = "Deletar";
}
<h1>@ViewData["Title"]</h1>


<div class="alert alert-info" role="alert">
    <h1>Computador @Model.Id Excluido</h1>
</div>

Views/Computer/Index.cshtml
@model IEnumerable<MvcLabManager.Models.Computer>

@{
    ViewData["Title"] = "Computadores";
}
<h1>@ViewData["Title"]</h1>

@if(Model.Count() == 0)
{
    <p>Nenhum computador cadastrado.</p>
}
else
{
    <table class="table">
        <thead> 
            <tr> 
                <th>Id</th>
                <th>RAM</th>
                <th>Processador</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var computer in Model)
            {
                <tr>
                    <td>@computer.Id</td>
                    <td>@computer.Ram</td>
                    <td>@computer.Processor</td>
                    <td> 
                        <a class="btn btn-primary btn-sm" asp-controller="Computer" asp-action="Show" asp-route-id="@computer.Id">Ver</a>
                        <a class="btn btn-secondary btn-sm" asp-controller="Computer" asp-action="Update" asp-route-id="@computer.Id">Editar</a>
                        <a class="btn btn-danger  btn-sm" asp-controller="Computer" asp-action="Delete" asp-route-id="@computer.Id">Excluir</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

Views/Computer/Show.cshtml
@model MvcLabManager.Models.Computer

@{
    ViewData["Title"] = $"Computador {Model.Id}";
}

<h1>@ViewData["Title"]</h1>

<p>Id: @Model.Id</p>
<p>RAM: @Model.Ram</p>
<p>Processador: @Model.Processor</p>

Views/Computer/Update.cshtml
@model MvcLabManager.Models.Computer

@{
    ViewData["Title"] = "Editar Computador";
}
<h1>@ViewData["Title"]</h1>


    <form method="post">
        <p>
            <label for="id"><strong>Id:</strong></label>
            <input asp-for="@Model.Id" readonly>
        </p>
        <p>
            <label for="ram"><strong>RAM: </strong></label>
            <input asp-for="@Model.Ram" required>
        </p>
          <p>
            <label for="processor"><strong>Processador: </strong></label>
            <input asp-for="@Model.Processor" required>
        </p>
       
        <button asp-controller="Computer" asp-action="Update" class="btn btn-outline-success">Atualizar</button>
    </form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Lab/Create.cshtml
@model MvcLabManager.Models.Lab

@{
    ViewData["Title"] = "Cadastrar Laboratório";
}
<h1>@ViewData["Title"]</h1>

    <form method="post">
        <p>
            <label for="id"><strong>Id:</strong></label>
            <input type="text" name="id" id="id">
            <span asp-validation-for="Id" class="text-danger" ></span>
        </p>
        <p>
            <label for="number"><strong>Número: </strong></label>
            <input type="number" name="number" id="number">
            <span asp-validation-for="Number" class="text-danger" ></span>
        </p>
        <p>
            <label for="name"><strong>Nome: </strong></label>
            <input type="text" name="name" id="name">
            <span asp-validation-for="Name" class="text-danger" ></span>
        </p>
         <p>
            <label for="block"><strong>Bloco: </strong></label>
            <input type="text" name="block" id="block">
            <span asp-validation-for="Block" class="text-danger" ></span>
        </p>

        <button asp-controller="Lab" asp-action="Create" class="btn btn-outline-success">Registrar</button>
    </form>

Views/Lab/Delete.cshtml
@model MvcLabManager.Models.Lab

@{
    ViewData["Title"] = "Deletar";
}
<h1>@ViewData["Title"]</h1>


<div class="alert alert-info" role="alert">
    <h1>Laboratório @Model.Id excluido com sucesso!</h1>
</div>

Views/Lab/Index.cshtml
@model IEnumerable<MvcLabManager.Models.Lab>

@{
    ViewData["Title"] = "Laboratórios";
}
<h1>@ViewData["Title"]</h1>

@if(Model.Count() == 0)
{
    <p>Nenhum laboratório cadastrado.</p>
}
else
{
    <table class="table">
        <thead> 
            <tr> 
                <th>Id</th>
                <th>Número</th>
                <th>Nome</th>
                <th>Bloco</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach(var lab in Model)
            {
                <tr>
                    <td>@lab.Id</td>
                    <td>@lab.Number</td>
                    <td>@lab.Name</td>
                    <td>@lab.Block</td>
                    <td> 
                        <a class="btn btn-primary   btn-sm" asp-controller="Lab" asp-action="Show" asp-route-id="@lab.Id">Ver</a>
                        <a class="btn btn-secondary btn-sm" asp-controller="Lab" asp-action="Update" asp-route-id="@lab.Id">Editar</a>
                        <a class="btn btn-danger    btn-sm" asp-controller="Lab" asp-action="Delete" asp-route-id="@lab.Id">Deletar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
}

Views/Lab/Show.cshtml
@model MvcLabManager.Models.Lab

@{
    //interpolação de string
    ViewData["Title"] = $"Laboratório {Model.Id}";
}
<h1>@ViewData["Title"]</h1>

<p>Id: @Model.Id</p>
<p>Número: @Model.Number</p>
<p>Nome: @Model.Name</p>
<p>Bloco: @Model.Block</p>

Views/Lab/Update.cshtml
@model MvcLabManager.Models.Lab

@{
    ViewData["Title"] = "Editar Laboratório";
}
<h1>@ViewData["Title"]</h1>


    <form method="post">
        <p>
            <label for="id"><strong>Id:</strong></label>
            <input asp-for="@Model.Id" readonly>
        </p>
        <p>
            <label for="number"><strong>Número: </strong></label>
            <input asp-for="@Model.Number" required>
        </p>
        <p>
            <label for="name"><strong>Nome: </strong></label>
            <input asp-for="@Model.Name" required>
        </p>
        <p>
            <label for="block"><strong>Bloco: </strong></label>
            <input asp-for="@Model.Block" required>
        </p>

        <button asp-controller="Lab" asp-action="Update" class="btn btn-outline-success">Atualizar</button>
    </form>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcLabManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcLabManager.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcLabManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MvcLabManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>